// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;
import '../constants.dart';

class DefaultFirebaseOptions {


  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: kApiKey,
    appId: '1:950229377498:web:ef0dfc6a875f3b3bd8a0e3',
    messagingSenderId: '950229377498',
    projectId: 'ecogram-bfd3e',
    authDomain: 'ecogram-bfd3e.firebaseapp.com',
    databaseURL: 'https://ecogram-bfd3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecogram-bfd3e.appspot.com',
    measurementId: 'G-8XTZDFJZEM',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: kApiKey,
    appId: '1:950229377498:android:ea0e16020c1fe946d8a0e3',
    messagingSenderId: '950229377498',
    projectId: 'ecogram-bfd3e',
    databaseURL: 'https://ecogram-bfd3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecogram-bfd3e.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: kApiKey,
    appId: '1:950229377498:ios:3d8f4bbad154d7d6d8a0e3',
    messagingSenderId: '950229377498',
    projectId: 'ecogram-bfd3e',
    databaseURL: 'https://ecogram-bfd3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecogram-bfd3e.appspot.com',
    iosClientId: '950229377498-q45on7q4j6lpkl2c1a3n85vrfad8dobo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecogram',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: kApiKey,
    appId: '1:950229377498:ios:3d8f4bbad154d7d6d8a0e3',
    messagingSenderId: '950229377498',
    projectId: 'ecogram-bfd3e',
    databaseURL: 'https://ecogram-bfd3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecogram-bfd3e.appspot.com',
    iosClientId: '950229377498-q45on7q4j6lpkl2c1a3n85vrfad8dobo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecogram',
  );
}
